-- create db + tables (sesuaikan nama db jika perlu)
CREATE DATABASE IF NOT EXISTS movies_db_rawMySQL_JWT;
USE movies_db_rawMySQL_JWT;

-- users
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- categories
CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  userId INT,
  CONSTRAINT fk_categories_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);

-- movies
CREATE TABLE IF NOT EXISTS movies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  year INT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  categoryId INT,
  userId INT,
  CONSTRAINT fk_movies_category FOREIGN KEY (categoryId) REFERENCES categories(id) ON DELETE SET NULL,
  CONSTRAINT fk_movies_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);

